version: '3.8'

services:
  nginx:
    image: nginx:1.19
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    networks:
      - rede
    ports:
      - "${NGINX}:80"
    depends_on:
      - app
  app:
    build: 
      context: ./
      dockerfile: ./builds/php-fpm.Dockerfile
    restart: always
    networks: 
      - rede
    volumes: 
      - ./src:/var/www/

networks:
  rede: